export const UPDATE_DOUGHS = "UPDATE_DOUGHS";
export const UPDATE_SIZES = "UPDATE_SIZES";
export const UPDATE_SAUCES = "UPDATE_SAUCES";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";
